import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { CountryCard } from "../components/CountryCard/CountryCard";
import { CountryPagination } from "../components/CountryPagination/CountryPagination";
import { getLayoutDefault } from "../layouts/LayoutDefault/LayoutDefault";
import { ICountryData } from "../layouts/LayoutDefault/LayoutDefault.types";

const Home = ({ data }: { data: ICountryData[] }): JSX.Element => {
  const [newData, setNewData] = useState<ICountryData[]>();
  const [isDataLoading, setIsDataLoading] = useState(false);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CountryCard data={newData || data} isDataLoading={isDataLoading} />
      <CountryPagination
        setNewData={setNewData}
        setIsDataLoading={setIsDataLoading}
      />
    </div>
  );
};

export default Home;

Home.getLayout = getLayoutDefault;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch("https://restcountries.com/v3.1/all");
  const data: ICountryData[] = await res.json();
  data.sort((a, b) => a.name.common.localeCompare(b.name.common));

  const sliceBegin = context.query.page
    ? 25 * (Number(context.query.page) - 1)
    : 0;
  const sliceEnd = context.query.page ? 25 * Number(context.query.page) : 25;

  const slicedData = data.slice(sliceBegin, sliceEnd);

  return { props: { data: slicedData } };
};
